version: "3.8"

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Cripto3851
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: